### ISSUE TITLE
Searching for information

### ISSUE THREAD

**Issue by PaulaLebedev** [PaulaLebedev/SleepingwithSirens#2]
- [x] About the band

- [x] About their history

- [x] About their Tour(s)

**Comment by hanspavelson** [comment]
API: https://app.swaggerhub.com/apis/Kooliprojekt/Sleepingwithsirens/1.0.0
INFO: https://en.wikipedia.org/wiki/Sleeping_with_Sirens
Koduleht: http://sirensmusic.co/
Spotify: https://open.spotify.com/artist/3N8Hy6xQnQv1F1XCiyGQqA
Itunes: https://music.apple.com/ee/album/how-it-feels-to-be-lost/1468968253?app=itunes&ign-mpt=uo%3D4
Google play: https://play.google.com/store/music/album/How_It_Feels_to_Be_Lost?id=Bwnuujjs4vrahvk4dvb5ik2ahje&hl=en_US
Merch: https://www.sumerianmerch.com/collections/sleeping-with-sirens
